##################################
###
### This project starts from centos:7 build and installs systemd (container) and latest docker
###
### - remount /sys/fs/cgroups within the context its launched into (side effect of --priv)
### - launches docker (Working how to let SystemD do this
### - passes control to SystemD (unless told to do otherwise)
###
### Ideas (and portions of code in the project) originated from
###  https://github.com/jpetazzo/dind
###  https://github.com/maci0/docker-systemd-unpriv
###
##################################

FROM rickalm/centos7:base-007
MAINTAINER Rick Alm "rickalm@aol.com"

# Install all of the external components as a single step to reduce layer size
# symlink the start_systemd script as entrypoint
#
RUN \
  \
  # Launch Docker through start script; \
  \
  systemctl enable \
    docker.service \
    docker.socket \
    || exit 1; \
  \
  ln -sf /start_systemd.sh /entrypoint.sh \
    || exit 1; \
  \
  /bin/true
