##################################
###
### This project starts from centos:7 build and installs systemd (container) and latest docker
###
### - remount /sys/fs/cgroups within the context its launched into (side effect of --priv)
### - launches docker (Working how to let SystemD do this
### - passes control to SystemD (unless told to do otherwise)
###
### Ideas (and portions of code in the project) originated from
###  https://github.com/jpetazzo/dind
###  https://github.com/maci0/docker-systemd-unpriv
###
##################################

FROM centos:centos7
MAINTAINER Rick Alm "rickalm@aol.com"

# declare /run and /sys/fs as volumes so they are not tied to overlayfs and therfore "remountable"
# declare /var/lib/docker as a volume so overlayfs doesnt get swamped with deltas
# 
VOLUME [ "/run", "/sys/fs/cgroup", "/var/lib/docker" ]
ENTRYPOINT  ["/start_dind.sh"]
CMD  ["/usr/lib/systemd/systemd"]
ENV container docker

# Split apart to improve docker build cache
#
RUN \
  yum -y update \
    || exit 1; \
  \
  # Swap out the "Containerized" SystemD for standard SystemD and add dbus; \
  \
  yum -y swap \
    -- remove systemd-container systemd-container-libs \
    -- install systemd systemd-libs dbus \
    || exit 1; \
  \
  # Install other tools we will need; \
  \
  yum -y install \
    lxc \
    less \
    iptables \
    || exit 1; \
  \
  # Cleanup YUM files to reduce image size; \
  \
  yum -y clean all \
    || exit 1; \
  \
  # Deactivate units that will not work in a container; \
  \
  systemctl mask \
    dev-mqueue.mount \
    dev-hugepages.mount \
    sys-kernel-config.mount \
    sys-kernel-debug.mount \
    sys-fs-fuse-connections.mount \
    systemd-remount-fs.service \
    display-manager.service \
    systemd-logind.service \
    console-getty.service \
    getty@tty1.service \
    graphical.target \
    || exit 1; \
  \
  # enable tmpfs in this container; \
  \
  systemctl enable \
    tmp.mount \
    || exit 1; \
  \
  # Install docker so we have a "DinD" environment; \
  \
  curl -sSL https://get.docker.com/ | sh \
    || exit 1; \
  \
  /bin/true

# Add our start scripts to the image
#
ADD files /
